using System.Collections.Generic;

namespace r1ft.Headlamps
{
    internal static class HeadLamps
    {
        public static string[] Objects = new[] {
            //opsCore BLACK
            "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_opsCore_fast_black(Clone)/mod_mount/item_equipment_helmet_opsCore_single_clamp_rail_adapter(Clone)/mod_flashlight/flashlight_ultrafire_WF-501B(Clone)/mode_001",
            "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_opsCore_fast_black(Clone)/mod_mount/item_equipment_helmet_opsCore_single_clamp_rail_adapter(Clone)/mod_flashlight/flashlight_armytek_predator_pro_v3_xhp35_hi(Clone)/mode_001",
            "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_opsCore_fast_black(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_surefire_x400_vis_laser(Clone)/mode_001",
            "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_opsCore_fast_black(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_zenit_2p_kleh_vis_laser(Clone)/mode_001",
            //opsCore TAN
            "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_opsCore_fast_tan(Clone)/mod_mount/item_equipment_helmet_opsCore_single_clamp_rail_adapter(Clone)/mod_flashlight/flashlight_ultrafire_WF-501B(Clone)/mode_001",
            "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_opsCore_fast_tan(Clone)/mod_mount/item_equipment_helmet_opsCore_single_clamp_rail_adapter(Clone)/mod_flashlight/flashlight_armytek_predator_pro_v3_xhp35_hi(Clone)/mode_001",
            "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_opsCore_fast_tan(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_surefire_x400_vis_laser(Clone)/mode_001",
            "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_opsCore_fast_tan(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_zenit_2p_kleh_vis_laser(Clone)/mode_001",
            //galvion
            "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_galvion_caiman(Clone)/mod_mount/item_equipment_helmet_opsCore_single_clamp_rail_adapter(Clone)/mod_flashlight/flashlight_ultrafire_WF-501B(Clone)/mode_001",
            "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_galvion_caiman(Clone)/mod_mount/item_equipment_helmet_opsCore_single_clamp_rail_adapter(Clone)/mod_flashlight/flashlight_armytek_predator_pro_v3_xhp35_hi(Clone)/mode_001",
            "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_galvion_caiman(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_surefire_x400_vis_laser(Clone)/mode_001",
            "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_galvion_caiman(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_zenit_2p_kleh_vis_laser(Clone)/mode_001",
            //mich2001
            "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_mich2001_od(Clone)/mod_mount/item_equipment_helmet_opsCore_single_clamp_rail_adapter(Clone)/mod_flashlight/flashlight_ultrafire_WF-501B(Clone)/mode_001",
            "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_mich2001_od(Clone)/mod_mount/item_equipment_helmet_opsCore_single_clamp_rail_adapter(Clone)/mod_flashlight/flashlight_armytek_predator_pro_v3_xhp35_hi(Clone)/mode_001",
            "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_mich2001_od(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_surefire_x400_vis_laser(Clone)/mode_001",
            "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_mich2001_od(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_zenit_2p_kleh_vis_laser(Clone)/mode_001",
            //mich2002
            "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_mich2002_od(Clone)/mod_mount/item_equipment_helmet_opsCore_single_clamp_rail_adapter(Clone)/mod_flashlight/flashlight_ultrafire_WF-501B(Clone)/mode_001",
            "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_mich2002_od(Clone)/mod_mount/item_equipment_helmet_opsCore_single_clamp_rail_adapter(Clone)/mod_flashlight/flashlight_armytek_predator_pro_v3_xhp35_hi(Clone)/mode_001",
            "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_mich2002_od(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_surefire_x400_vis_laser(Clone)/mode_001",
            "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_mich2002_od(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_zenit_2p_kleh_vis_laser(Clone)/mode_001",
            //tc800
            "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_tc800(Clone)/mod_mount/item_equipment_helmet_opsCore_single_clamp_rail_adapter(Clone)/mod_flashlight/flashlight_ultrafire_WF-501B(Clone)/mode_001",
            "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_tc800(Clone)/mod_mount/item_equipment_helmet_opsCore_single_clamp_rail_adapter(Clone)/mod_flashlight/flashlight_armytek_predator_pro_v3_xhp35_hi(Clone)/mode_001",
            "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_tc800(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_surefire_x400_vis_laser(Clone)/mode_001",
            "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_tc800(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_zenit_2p_kleh_vis_laser(Clone)/mode_001",
            //nfm
            "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_nfm_hjelm(Clone)/mod_mount/item_equipment_helmet_opsCore_single_clamp_rail_adapter(Clone)/mod_flashlight/flashlight_ultrafire_WF-501B(Clone)/mode_001",
            "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_nfm_hjelm(Clone)/mod_mount/item_equipment_helmet_opsCore_single_clamp_rail_adapter(Clone)/mod_flashlight/flashlight_armytek_predator_pro_v3_xhp35_hi(Clone)/mode_001",
            "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_nfm_hjelm(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_surefire_x400_vis_laser(Clone)/mode_001",
            "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_nfm_hjelm(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_zenit_2p_kleh_vis_laser(Clone)/mode_001",
            //LSHZ
            "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_LSHZ(Clone)/mod_mount/item_equipment_helmet_opsCore_single_clamp_rail_adapter(Clone)/mod_flashlight/flashlight_ultrafire_WF-501B(Clone)/mode_001",
            "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_LSHZ(Clone)/mod_mount/item_equipment_helmet_opsCore_single_clamp_rail_adapter(Clone)/mod_flashlight/flashlight_armytek_predator_pro_v3_xhp35_hi(Clone)/mode_001",
            "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_LSHZ(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_surefire_x400_vis_laser(Clone)/mode_001",
            "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_LSHZ(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_zenit_2p_kleh_vis_laser(Clone)/mode_001",
            //FASTMT
            "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_hops_core_fast(Clone)/mod_mount/item_equipment_helmet_opsCore_single_clamp_rail_adapter(Clone)/mod_flashlight/flashlight_ultrafire_WF-501B(Clone)/mode_001",
            "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_hops_core_fast(Clone)/mod_mount/item_equipment_helmet_opsCore_single_clamp_rail_adapter(Clone)/mod_flashlight/flashlight_armytek_predator_pro_v3_xhp35_hi(Clone)/mode_001",
            "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_hops_core_fast(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_surefire_x400_vis_laser(Clone)/mode_001",
            "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_hops_core_fast(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_zenit_2p_kleh_vis_laser(Clone)/mode_001",
            //AIRFRAME
            "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_crye_airframe_tan(Clone)/mod_mount/item_equipment_helmet_opsCore_single_clamp_rail_adapter(Clone)/mod_flashlight/flashlight_ultrafire_WF-501B(Clone)/mode_001",
            "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_crye_airframe_tan(Clone)/mod_mount/item_equipment_helmet_opsCore_single_clamp_rail_adapter(Clone)/mod_flashlight/flashlight_armytek_predator_pro_v3_xhp35_hi(Clone)/mode_001",
            "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_crye_airframe_tan(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_surefire_x400_vis_laser(Clone)/mode_001",
            "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_crye_airframe_tan(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_zenit_2p_kleh_vis_laser(Clone)/mode_001",
        };

        public static Dictionary<string, string> AltMode = new Dictionary<string, string>()
        {
            //opsCore BLACK
            { "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_opsCore_fast_black(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_surefire_x400_vis_laser(Clone)/mode_001", "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_opsCore_fast_black(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_surefire_x400_vis_laser(Clone)/mode_002" },
            { "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_opsCore_fast_black(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_zenit_2p_kleh_vis_laser(Clone)/mode_001", "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_opsCore_fast_black(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_zenit_2p_kleh_vis_laser(Clone)/mode_002" },
            //opsCore TAN
            { "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_opsCore_fast_tan(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_surefire_x400_vis_laser(Clone)/mode_001", "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_opsCore_fast_tan(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_surefire_x400_vis_laser(Clone)/mode_002"},
            { "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_opsCore_fast_tan(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_zenit_2p_kleh_vis_laser(Clone)/mode_001", "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_opsCore_fast_tan(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_zenit_2p_kleh_vis_laser(Clone)/mode_002"},
            //galvion
            { "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_galvion_caiman(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_surefire_x400_vis_laser(Clone)/mode_001","PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_galvion_caiman(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_surefire_x400_vis_laser(Clone)/mode_002" },
            { "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_galvion_caiman(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_zenit_2p_kleh_vis_laser(Clone)/mode_001","PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_galvion_caiman(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_zenit_2p_kleh_vis_laser(Clone)/mode_002" },
            //mich2001
            { "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_mich2001_od(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_surefire_x400_vis_laser(Clone)/mode_001", "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_mich2001_od(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_surefire_x400_vis_laser(Clone)/mode_002" },
            { "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_mich2001_od(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_zenit_2p_kleh_vis_laser(Clone)/mode_001", "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_mich2001_od(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_zenit_2p_kleh_vis_laser(Clone)/mode_002" },
            //mich2002
            { "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_mich2002_od(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_surefire_x400_vis_laser(Clone)/mode_001", "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_mich2002_od(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_surefire_x400_vis_laser(Clone)/mode_002" },
            { "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_mich2002_od(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_zenit_2p_kleh_vis_laser(Clone)/mode_001", "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_mich2002_od(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_zenit_2p_kleh_vis_laser(Clone)/mode_002" },
            //tc800
            { "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_tc800(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_surefire_x400_vis_laser(Clone)/mode_001", "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_tc800(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_surefire_x400_vis_laser(Clone)/mode_002" },
            { "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_tc800(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_zenit_2p_kleh_vis_laser(Clone)/mode_001", "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_tc800(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_zenit_2p_kleh_vis_laser(Clone)/mode_002" },
            //nfm
            { "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_nfm_hjelm(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_surefire_x400_vis_laser(Clone)/mode_001", "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_nfm_hjelm(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_surefire_x400_vis_laser(Clone)/mode_002" },
            { "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_nfm_hjelm(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_zenit_2p_kleh_vis_laser(Clone)/mode_001", "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_nfm_hjelm(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_zenit_2p_kleh_vis_laser(Clone)/mode_002" },
            //LSHZ
            { "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_LSHZ(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_surefire_x400_vis_laser(Clone)/mode_001", "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_LSHZ(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_surefire_x400_vis_laser(Clone)/mode_002" },
            { "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_LSHZ(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_zenit_2p_kleh_vis_laser(Clone)/mode_001","PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_LSHZ(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_zenit_2p_kleh_vis_laser(Clone)/mode_002" },
            //FASTMT
            { "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_hops_core_fast(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_surefire_x400_vis_laser(Clone)/mode_001","PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_hops_core_fast(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_surefire_x400_vis_laser(Clone)/mode_002" },
            { "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_hops_core_fast(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_zenit_2p_kleh_vis_laser(Clone)/mode_001", "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_hops_core_fast(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_zenit_2p_kleh_vis_laser(Clone)/mode_002" },
            //AIRFRAME
            { "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_crye_airframe_tan(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_surefire_x400_vis_laser(Clone)/mode_001", "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_crye_airframe_tan(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_surefire_x400_vis_laser(Clone)/mode_002" },
            { "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_crye_airframe_tan(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_zenit_2p_kleh_vis_laser(Clone)/mode_001", "PlayerSuperior(Clone)/Player/Root_Joint/Base HumanPelvis/Base HumanSpine1/Base HumanSpine2/Base HumanSpine3/Base HumanNeck/Base HumanHead/item_equipment_helmet_crye_airframe_tan(Clone)/mod_mount/item_equipment_helmet_opsCore_picatinny_rail_adapter(Clone)/mod_mount/tactical_all_zenit_2p_kleh_vis_laser(Clone)/mode_002" },
        };
    }
}
